// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmudrpyjngcznnqqjlbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdWRycHlqbmdjem5ucXFqbGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzIwOTUsImV4cCI6MjA2OTIwODA5NX0.CfOv_02V_uZeasG9jnvMesR6D3kWUdMxpLkqjiavl6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});